version: '3.11.2'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - ./todoapp:/usr/src/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
